package severification.alf.model;

public enum InstructionType {
	CREATE_OBJECT, DESTROY_OBJECT, ADD_STRUCTURAL_FEATURE, CREATE_LINK, DESTROY_LINK, CLEAR_ASSOCIATION, RECLASSIFY_OBJECT , EMPTY
}
