/*
 * generated by Xtext
 */
package org.xtext.alf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlfRuntimeModule extends org.xtext.alf.AbstractAlfRuntimeModule {

}
