/*
* generated by Xtext
*/
package org.xtext.alf.ui.contentassist;

import org.xtext.alf.ui.contentassist.AbstractAlfProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AlfProposalProvider extends AbstractAlfProposalProvider {

}
