
/*
 * generated by Xtext
 */
 
package org.xtext.alf.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class AlfExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.xtext.alf.ui.internal.AlfActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.xtext.alf.ui.internal.AlfActivator.getInstance().getInjector("org.xtext.alf.Alf");
	}
	
}
